name: cvlab_pix2pix
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - nvidia::cudatoolkit=11.1
  - python=3.8
  - pytorch::pytorch=1.8.1
  - scipy
  - pip
  - pip:    
      - appdirs==1.4.4
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - docker-pycreds==0.4.0
      - dominate==2.9.1
      - filelock==3.13.1
      - fsspec==2023.12.2
      - gitdb==4.0.11
      - gitpython==3.1.40
      - idna==3.6
      - imageio==2.33.1
      - jinja2==3.1.2
      - jsonpatch==1.33
      - jsonpointer==2.4
      - lazy-loader==0.3
      - markupsafe==2.1.3
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.4
      - opencv-python==4.9.0.80
      - packaging==23.2
      - pillow==10.2.0
      - protobuf==4.25.1
      - psutil==5.9.7
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - requests==2.31.0
      - sentry-sdk==1.39.1
      - setproctitle==1.3.3
      - smmap==5.0.1
      - sympy==1.12
      - tifffile==2023.7.10
      - torchvision==0.9.1
      - tornado==6.4
      - urllib3==2.1.0
      - visdom==0.2.4
      - wandb==0.16.1
      - websocket-client==1.7.0
      - scikit-image==0.21.0